intents:
  - intent:
      tag: greetings
      patterns:
        - hello
        - hey
        - hi
        - greetings
        - whats up?
        - what's up?
        - hey hey
        - hey what's up?
        - how is it going?
      responses:
        - Hey hey
        - Hello
        - Hey how are you?
        - Hi
        - hey, how may I help you
  - intent:
      tag: goodbye
      patterns:
        - bye
        - bye bye
        - goodbye
        - good-bye
        - see ya
        - see you later
        - see you soon
        - see you again
        - until tomorrow
        - have a good day
        - have a good one
      responses:
        - Bye Human
        - See you
        - See you again later
        - goodbye
        - okay, see you
        - anytime you need, i'll be here
